export const FETCH_ALL_CONTESTS_REQUEST = "FETCH_ALL_CONTESTS_REQUEST";
export const FETCH_ALL_CONTESTS_SUCCESS = "FETCH_ALL_CONTESTS_SUCCESS";
export const FETCH_ALL_CONTESTS_FAILURE = "FETCH_ALL_CONTESTS_FAILURE";
export const FETCH_USER_SUBMISSIONS = "FETCH_USER_SUBMISSIONS";
export const VIEW_USER_CODE = "VIEW_USER_CODE";
