export const SUBMIT_PAGE_ROUTE_REQUEST = "SUBMIT_PAGE_ROUTE_REQUEST";
export const SUBMIT_PAGE_ROUTE_EXIT = "SUBMIT_PAGE_ROUTE_EXIT";
export const SUBMIT_CODE_REQUEST = "SUBMIT_CODE_REQUEST";
export const SUBMIT_CODE_SUCCESS = "SUBMIT_CODE_SUCCESS";
export const SUBMIT_CODE_FAILURE = "SUBMIT_CODE_FAILURE";
export const EVENT_CODE_REQUEST = "EVENT_CODE_REQUEST";
export const EVENT_CODE_SUCCESS = "EVENT_CODE_SUCCESS";
export const EVENT_CODE_FAILURE = "EVENT_CODE_FAILURE";
